### ISSUE TITLE
Cannot start 3 container

### ISSUE THREAD

**Issue by tuanpt89** [thepower/test_shard#1]
3 container all show status is Restating after docker-compose up
![screenshot_1666888033](https://user-images.githubusercontent.com/27726563/198346453-9047ac36-c0f7-40cc-b21b-0c59019e62a4.png)

**Comment by revoks** [comment]
Hi! Please try this:
- stop all containers
- remove all docker images
- and just run:
`docker run -d -p 44000:44000 --name testnet thepowerio/tpnode`
- then check the output of the command
`curl http://localhost:44000/api/node/status | jq`
